---
kind: pipeline
name: node-carbon

steps:
- name: build
  image: node:carbon-alpine
  commands:
    - apk add git python2
    - npm install -g codecov
    - npm ci
- name: test
  image: node:carbon-alpine
  commands:
    - npm run test-travis
- name: coverage
  image: node:carbon-alpine
  commands:
    - npm run coverage

---
kind: pipeline
name: node-dubnium

steps:
- name: build
  image: node:dubnium-alpine
  commands:
    - apk add git python2
    - npm install -g codecov
    - npm ci
- name: test
  image: node:dubnium-alpine
  commands:
    - npm run test-travis
- name: coverage
  image: node:dubnium-alpine
  commands:
    - npm run coverage


