pipeline:
  build:
    image: node:6.12.3
    commands: 
      - nvm install 6
      - npm install -g codecov

  sdk-test:
    group: test
    image: node:6.12.3
    commands: 
      - npm run test-travis

  coverage:
    group: test
    image: node:6.12.3
    commands: 
      - npm run coverage
