pipeline:
  sdk build:
    image: node:10.15.3
    commands: 
      - nvm install 10
      - npm install -g codecov
      - npm ci

  sdk run sdk-test:
    group: test
    image: node:10.15.3
    commands: 
      - npm run test-travis
      - npm run test-node

  sdk run coverage:
    group: test
    image: node:10.15.3
    commands: 
      - npm run coverage
