pipeline:
  Node.js 10:
    image: ubuntu:latest
    commands: 
      - apt-get update
      - apt-get upgrade -y
      - apt-get install dialog -y
      - apt-get install wget -y
      - wget -qO- https://raw.githubusercontent.com/creationix/nvm/v0.34.0/install.sh | bash
      - echo '#!/usr/bin/env bash' | cat - /root/.bashrc > temp && mv temp /root/.bashrc
      - . /root/.bashrc && nvm install 10
      - npm install -g codecov
      - npm ci
      - npm run test-travis
