pipeline:
  Node.js 10:
    image: ubuntu:latest
    commands: 
      - apt-get update
      - apt-get upgrade -y
      - apt-get install dialog wget npm nodejs -y
      - npm install -g codecov
      - npm ci
      - npm run test-travis
