pipeline:
  sdk build:
    image: alpine:latest
    commands: 
      - /sbin/apk add curl bash npm
      - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.32.1/install.sh | bash
      - export NVM_DIR="/root/.nvm" && . "$NVM_DIR/nvm.sh"
      - nvm install 10
      - npm install -g codecov
      - npm ci

  sdk run sdk-test:
    group: test
    image: alpine:latest
    commands: 
      - npm run test-travis
      - npm run test-node

  sdk run coverage:
    group: test
    image: alpine:latest
    commands: 
      - npm run coverage
