pipeline:
  node 6:
    image: garyyang6/ubuntu_nvm:latest
    commands: 
      - apt-get install git python make -y
      - export NVM_DIR="/root/.nvm/versions/node/v6.17.0/bin" 
      - export PATH=$NVM_DIR:$PATH
      - export BITGOJS_TEST_PASSWORD=[secure]
      - node --version
      - npm --version
      - npm install -g codecov
      - npm install
      - npm run test-travis
      - npm run coverage
