pipeline:
  sdk build:
    image: garyyang6/ubuntu_nvm:latest
    commands: 
      - apt-get update
      - apt-get upgrade -y
      - apt-get install curl bash -y
      - cat ~/.bashrc
      - ls ~/.nvm/versions/node
      - nvm install 6
      - npm install -g codecov

