pipeline:
  sdk build:
    image: node:6.12.3
    commands: 
      - apk add curl
      - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.32.1/install.sh | bash
      - export NVM_DIR="/root/.nvm" 
      - [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
      - nvm install 10
      - npm install -g codecov
      - npm ci

  sdk run sdk-test:
    group: test
    image: node:6.12.3
    commands: 
      - npm run test-travis
      - npm run test-node

  sdk run coverage:
    group: test
    image: node:6.12.3
    commands: 
      - npm run coverage
