pipeline:
  Node.js 10:
    image: ubuntu:latest
    commands: 
      - apt-get update
      - apt-get upgrade -y
      - apt-get install dialog -y
      - apt-get install wget -y
      - apt-get install npm -y
      - apt-get install nodejs -y
      - wget -qO- https://raw.githubusercontent.com/creationix/nvm/v0.34.0/install.sh | bash
      - source ~/.profile
      - nvm install 10
      - npm install -g codecov
      - npm ci
      - npm run test-travis
