---
kind: pipeline
name: audit

platform:
  os: linux
  arch: amd64

steps:
- name: build information
  image: node:lts
  commands:
  - node --version
  - npm --version

- name: install
  image: node:lts
  commands:
  - lerna bootstrap

- name: audit
  image: node:lts
  commands:
  - lerna run audit

---
kind: pipeline
name: lint

platform:
  os: linux
  arch: amd64

steps:
- name: build information
  image: node:lts
  commands:
  - node --version
  - npm --version

- name: install
  image: node:lts
  commands:
  - lerna bootstrap

- name: lint
  image: node:lts
  commands:
  - lerna run lint

---
kind: pipeline
name: unit tests (node:6)

platform:
  os: linux
  arch: amd64

steps:
- name: build information
  image: node:6
  commands:
  - node --version
  - npm --version

- name: install
  image: node:6
  commands:
  - lerna bootstrap

- name: unit tests
  image: node:6
  commands:
  - lerna run unit-test
  environment:
    BITGOJS_TEST_PASSWORD:
      from_secret: password

- name: upload coverage
  image: node:6
  commands:
  - npm install -g codecov
  - lerna run gen-coverage
  - lerna run upload-coverage -- -F unit
  environment:
    CODECOV_TOKEN:
      from_secret: codecov
  when:
    branch:
    - master
    - "rel/*"
    - prod/production

---
kind: pipeline
name: unit tests (node:8)

platform:
  os: linux
  arch: amd64

steps:
- name: build information
  image: node:8
  commands:
  - node --version
  - npm --version

- name: install
  image: node:8
  commands:
  - lerna bootstrap

- name: unit tests
  image: node:8
  commands:
  - lerna run unit-test
  environment:
    BITGOJS_TEST_PASSWORD:
      from_secret: password

- name: upload coverage
  image: node:8
  commands:
  - npm install -g codecov
  - lerna run gen-coverage
  - lerna run upload-coverage -- -F unit
  environment:
    CODECOV_TOKEN:
      from_secret: codecov
  when:
    branch:
    - master
    - "rel/*"
    - prod/production

---
kind: pipeline
name: unit tests (node:9)

platform:
  os: linux
  arch: amd64

steps:
- name: build information
  image: node:9
  commands:
  - node --version
  - npm --version

- name: install
  image: node:9
  commands:
  - lerna bootstrap

- name: unit tests
  image: node:9
  commands:
  - lerna run unit-test
  environment:
    BITGOJS_TEST_PASSWORD:
      from_secret: password

- name: upload coverage
  image: node:9
  commands:
  - npm install -g codecov
  - lerna run gen-coverage
  - lerna run upload-coverage -- -F unit
  environment:
    CODECOV_TOKEN:
      from_secret: codecov
  when:
    branch:
    - master
    - "rel/*"
    - prod/production

---
kind: pipeline
name: unit tests (node:10)

platform:
  os: linux
  arch: amd64

steps:
- name: build information
  image: node:10
  commands:
  - node --version
  - npm --version

- name: install
  image: node:10
  commands:
  - lerna bootstrap

- name: unit tests
  image: node:10
  commands:
  - lerna run unit-test
  environment:
    BITGOJS_TEST_PASSWORD:
      from_secret: password

- name: upload coverage
  image: node:10
  commands:
  - npm install -g codecov
  - lerna run gen-coverage
  - lerna run upload-coverage -- -F unit
  environment:
    CODECOV_TOKEN:
      from_secret: codecov
  when:
    branch:
    - master
    - "rel/*"
    - prod/production

---
kind: pipeline
name: unit tests (node:11)

platform:
  os: linux
  arch: amd64

steps:
- name: build information
  image: node:11
  commands:
  - node --version
  - npm --version

- name: install
  image: node:11
  commands:
  - lerna bootstrap

- name: unit tests
  image: node:11
  commands:
  - lerna run unit-test
  environment:
    BITGOJS_TEST_PASSWORD:
      from_secret: password

- name: upload coverage
  image: node:11
  commands:
  - npm install -g codecov
  - lerna run gen-coverage
  - lerna run upload-coverage -- -F unit
  environment:
    CODECOV_TOKEN:
      from_secret: codecov
  when:
    branch:
    - master
    - "rel/*"
    - prod/production

---
kind: pipeline
name: integration tests (node:10)

platform:
  os: linux
  arch: amd64

steps:
- name: build information
  image: node:10
  commands:
  - node --version
  - npm --version
  when:
    branch:
    - master
    - "rel/*"
    - prod/production

- name: install
  image: node:10
  commands:
  - lerna bootstrap
  when:
    branch:
    - master
    - "rel/*"
    - prod/production

- name: integration tests
  image: node:10
  commands:
  - lerna run integration-test
  environment:
    BITGOJS_TEST_PASSWORD:
      from_secret: password
  when:
    branch:
    - master
    - "rel/*"
    - prod/production

- name: upload coverage
  image: node:10
  commands:
  - npm install -g codecov
  - lerna run gen-coverage
  - lerna run upload-coverage -- -F integration
  environment:
    CODECOV_TOKEN:
      from_secret: codecov
  when:
    branch:
    - master
    - "rel/*"
    - prod/production

---
kind: pipeline
name: size and timing (node:lts)

platform:
  os: linux
  arch: amd64

steps:
- name: slow-deps
  image: node:lts
  commands:
  - npm install -g slow-deps
  - slow-deps

...
