---
kind: pipeline
name: NODE6

secrets:
   - password

steps:
   - name: node 6.17.0
     image: node:6.17.0
     secrets:
        - password
     commands:
        - export BITGOJS_TEST_PASSWORD=$PASSWORD
        - npm --version
        - npm install -g codecov
        - npm instaLL
        - npm run test-travis

---
kind: pipeline
name: NODE8

steps:
   - name: node 8.15.1
     image: node:8.15.1
     secrets:
        - password
     commands:
        - export BITGOJS_TEST_PASSWORD=$PASSWORD
        - npm --version
        - npm install -g codecov
        - npm install
        - npm run test-travis
