---
kind: pipeline
name: NODE8

secrets:
   - password

steps:
   - name: node 8.15.1
     image: node:8.15.1
     secrets:
        - password
     environment:
        - BITGOJS_TEST_PASSWORD=$PASSWORD
     commands:
        - export BITGOJS_TEST_PASSWORD=$PASSWORD
        - node --version
        - npm --version
        - npm install -g codecov
        - npm install
        - npm run test-travis
---
kind: pipeline
name: NODE11

secrets:
   - password

steps:
   - name: node 11.12.0
     image: node:11.12.0
     secrets:
        - password
     environment:
        - BITGOJS_TEST_PASSWORD=$PASSWORD
     commands:
        - export BITGOJS_TEST_PASSWORD=$PASSWORD
        - node --version
        - npm --version
        - npm install -g codecov
        - npm instaLL
        - npm run test-travis

