pipeline:
  Node.js 10:
    image: ubuntu:18.10
    commands: 
      - apt-get update
      - apt-get upgrade -y
      - apt-get install dialog wget -y
      - wget -qO- https://raw.githubusercontent.com/creationix/nvm/v0.34.0/install.sh | bash
      - export NVM_DIR="$HOME/.nvm" && \. "$NVM_DIR/nvm.sh" &&  \. "$NVM_DIR/bash_completion" && nvm install lts/carbon && nvm install 10
      - npm install -g codecov
      - npm ci
      - npm run test-travis
