pipeline:
  node 6:
    image: garyyang6/ubuntu_nvm:latest
    environment: 
      - NVM_DIR="/root/.nvm/versions/node/v6.17.0/bin" 
      - PATH=${NVM_DIR}:$PATH

    commands: 
      - ls /root/.nvm/versions/node/v6.17.0/bin
      - ls $NVM_DIR
      - node --version
      - npm --version
      - npm install -g codecov
      - npm install
      - npm run test-travis
      - npm run coverage
